### LISTAR LIVROS
# GET http://localhost:5291/api/livros/listar

###
fetch('http://localhost:5291/api/livros/listar', {
  method: 'GET',
  mode: 'no-cors'
})
  .then(response => {
    // Processar a resposta
  })
  .catch(error => {
    // Lidar com o erro
  });

### LISTAR USUARIOS
GET http://localhost:5291/api/usuarios/listar

### LISTAR EMPRESTIMOS
GET http://localhost:5291/api/emprestimos/listar

### CADASTRAR LIVRO
POST http://localhost:5291/api/livro/cadastrar
Content-Type: application/json

{
    "titulo" : "As Aventuras do Antonio",
    "quantidadelivro" : 35,
    "autor": "Gabriel",
    "anopublicacao" : 2010
    
}

### CADASTRAR USUARIO
POST http://localhost:5291/api/usuario/cadastrar
Content-Type: application/json

{
    "nome": "Antonio",
    "email" : "antonio@gmail.com"
    
}

### CADASTRAR EMPRESTIMO
POST http://localhost:5291/api/emprestimo/cadastrar
Content-Type: application/json

{
    "livroId": "f372370b-47cc-4d6d-97d3-73cc68977b62",
    "usuarioId" : "6cf4761b-ae90-4f30-b71e-57f83e3e2e09",
    "dataemprestimo" : "18/05/2024",
    "datadevolucao" : "25/05/2024"
}

### ALTERAR USUARIO
PUT http://localhost:5291/api/usuario/alterar/f1f28d1a-f612-47dc-8538-6e4d5a307913
Content-Type: application/json

{
    "nome": "Cleyton",
    "email" : "Cleyton@gmail.com"
    
}

### DELETAR LIVRO
DELETE http://localhost:5291/api/livro/deletar/10899f6e-2f9a-4553-ac69-efcbc7722847

### DELETAR USUARIO
DELETE http://localhost:5291/api/usuario/deletar/fa5e91fe-911d-4881-ad35-0b8d5bcc10aa

### DELETAR EMPRESTIMO
DELETE http://localhost:5291/api/emprestimo/deletar/2b6fa79b-52b6-4dac-bd64-0c0f08f808a1

### DELETAR TODOS OS EMPRESTIMOS
DELETE http://localhost:5291/api/emprestimo/deletartudo

### DELETAR TODOS OS USUARIOS
DELETE http://localhost:5291/api/usuario/deletartudo

### DELETAR TODOS OS LIVROS
DELETE http://localhost:5291/api/livro/deletartudo
